spring:
  datasource:
    url: jdbc:mysql:///:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: zalwlf
    password: wsmengen521
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


